driver:
  name: <%= ENV['KI_DRIVER'] || 'vagrant' %>

verifier:
  name: inspec

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always

platforms:
  - name: centos-6.9
  - name: centos-7.4
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9
  - name: debian-8

suites:
  - name: default-deb
    run_list:
      - recipe[apt]
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.6"
      rabbitmq:
        version: "3.7.6"
    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["centos-6.9", "centos-7.4"]

  - name: default-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "20.3.6-1"
      rabbitmq:
        version: "3.7.6"

    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["ubuntu-16.04", "ubuntu-18.04", "debian-9"]

  - name: lwrps
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::lwrps]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.6"
      rabbitmq:
        version: "3.7.6"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/lwrps
    excludes: ["centos-6.9", "centos-7.4", "debian-9", "ubuntu-16.04"]

  - name: cluster-deb
    run_list:
      - recipe[apt]
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.6"
      rabbitmq:
        version: "3.7.6"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/cluster
    excludes: ["centos-6.9", "centos-7.4"]

  - name: cluster-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "20.3.6-1"
      rabbitmq:
        version: "3.7.6"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/cluster
    excludes: ["ubuntu-16.04", "ubuntu-18.04", "debian-9"]

  - name: default-force-yes
    run_list:
      - recipe[apt]
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.6"
      rabbitmq:
        version: "3.7.6"
    attributes:
      apt:
        confd:
          assume_yes: true
          force-yes: true
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.6"
      rabbitmq:
        version: "3.7.6"
    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["centos-6.9", "centos-7.4", "debian-9", "ubuntu-16.04"]

  - name: default-force-yes-false
    run_list:
      - recipe[apt]
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      apt:
        confd:
          assume_yes: false
          force-yes: false
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.6"
      rabbitmq:
        version: "3.7.6"
    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["centos-6.9", "centos-7.4", "debian-9", "ubuntu-16.04"]
  - name: rabbit1
    driver:
      network:
        - ["private_network", {ip: "10.10.10.4"}]
    run_list:
      - role[master_rmq_3.7.7]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    excludes: ["centos-6.9", "centos-7.4", "debian-9", "ubuntu-16.04", "ubuntu-18.04"]