AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

AsciiComments:
  Enabled: false

MethodLength:
  Max: 18

Style/FileName:
  Enabled: false

Metrics/AbcSize:
  Max: 16

Metrics/ModuleLength:
  Exclude:
    - "providers/*.rb"
    - "spec/*.rb"
    - "test/cookbooks/rabbitmq_test/files/default/tests/minitest/default_test.rb"
    - "test/cookbooks/rabbitmq_test/files/default/tests/minitest/lwrps_test.rb"

Metrics/BlockLength:
  Exclude:
    - "providers/*.rb"
    - "spec/*.rb"
    - "test/cookbooks/rabbitmq_test/files/default/tests/minitest/default_test.rb"
    - "test/cookbooks/rabbitmq_test/files/default/tests/minitest/lwrps_test.rb"
